apiVersion: v1
kind: Service
metadata:
  name: user-auth-api-deployment
spec:
  type: LoadBalancer
  selector:
    app: user-auth-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http